//
// Generated file, do not edit! Created by opp_msgc 4.3 from other/sensedresult.msg.
//

#ifndef _SENSEDRESULT_M_H_
#define _SENSEDRESULT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "measurement.h"
    typedef std::list<Measurement> MeasurementList;
// }}



/**
 * Class generated from <tt>other/sensedresult.msg</tt> by opp_msgc.
 * <pre>
 * message SensedResult {
 *     MeasurementList meaList;
 * }
 * </pre>
 */
class SensedResult : public ::cMessage
{
  protected:
    MeasurementList meaList_var;

  private:
    void copy(const SensedResult& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SensedResult&);

  public:
    SensedResult(const char *name=NULL, int kind=0);
    SensedResult(const SensedResult& other);
    virtual ~SensedResult();
    SensedResult& operator=(const SensedResult& other);
    virtual SensedResult *dup() const {return new SensedResult(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual MeasurementList& getMeaList();
    virtual const MeasurementList& getMeaList() const {return const_cast<SensedResult*>(this)->getMeaList();}
    virtual void setMeaList(const MeasurementList& meaList);
};

inline void doPacking(cCommBuffer *b, SensedResult& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SensedResult& obj) {obj.parsimUnpack(b);}


#endif // _SENSEDRESULT_M_H_
