//
// Generated file, do not edit! Created by opp_msgc 4.3 from packetemrp.msg.
//

#ifndef _PACKETEMRP_M_H_
#define _PACKETEMRP_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packetemrp.msg</tt> by opp_msgc.
 * <pre>
 * packet PacketEMRP {
 *     int someField;
 *     string anotherField;
 * }
 * </pre>
 */
class PacketEMRP : public ::cPacket
{
  protected:
    int someField_var;
    opp_string anotherField_var;

  private:
    void copy(const PacketEMRP& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketEMRP&);

  public:
    PacketEMRP(const char *name=NULL, int kind=0);
    PacketEMRP(const PacketEMRP& other);
    virtual ~PacketEMRP();
    PacketEMRP& operator=(const PacketEMRP& other);
    virtual PacketEMRP *dup() const {return new PacketEMRP(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSomeField() const;
    virtual void setSomeField(int someField);
    virtual const char * getAnotherField() const;
    virtual void setAnotherField(const char * anotherField);
};

inline void doPacking(cCommBuffer *b, PacketEMRP& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PacketEMRP& obj) {obj.parsimUnpack(b);}


#endif // _PACKETEMRP_M_H_
