//
// Generated file, do not edit! Created by opp_msgc 4.3 from wsnpacket.msg.
//

#ifndef _WSNPACKET_M_H_
#define _WSNPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>wsnpacket.msg</tt> by opp_msgc.
 * <pre>
 * packet WsnPacket {
 *     int srcAddr; 
 *     int desAddr; 
 *     int frameSize; 
 * }
 * </pre>
 */
class WsnPacket : public ::cPacket
{
  protected:
    int srcAddr_var;
    int desAddr_var;
    int frameSize_var;

  private:
    void copy(const WsnPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WsnPacket&);

  public:
    WsnPacket(const char *name=NULL, int kind=0);
    WsnPacket(const WsnPacket& other);
    virtual ~WsnPacket();
    WsnPacket& operator=(const WsnPacket& other);
    virtual WsnPacket *dup() const {return new WsnPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr);
    virtual int getDesAddr() const;
    virtual void setDesAddr(int desAddr);
    virtual int getFrameSize() const;
    virtual void setFrameSize(int frameSize);
};

inline void doPacking(cCommBuffer *b, WsnPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, WsnPacket& obj) {obj.parsimUnpack(b);}


#endif // _WSNPACKET_M_H_
